name: pull request
run-name: pull request
on: pull_request
permissions:
  contents: read
jobs:
  unit_test:
    name: Rust unit tests
    runs-on: [self-hosted, linux, x64]
    container:
      image: rust:1.93.0-alpine
    steps:
      - uses: actions/checkout@v4
      - run: apk add musl-dev
      - run: cargo test
  clippy:
    name: Clippy
    runs-on: [self-hosted, linux, x64]
    container:
      image: rust:1.93.0-alpine
    steps:
      - uses: actions/checkout@v4
      - run: apk add musl-dev
      - run: rustup target add wasm32-unknown-unknown
      - run: rustup component add clippy
      - run: cargo clippy --target wasm32-unknown-unknown -- -D warnings
  fmt:
    name: rustfmt
    runs-on: [self-hosted, linux, x64]
    container:
      image: rust:1.93.0-alpine
    steps:
      - uses: actions/checkout@v4
      - run: apk add musl-dev
      - run: rustup component add rustfmt
      - run: rustup target add wasm32-unknown-unknown
      - run: cargo install -f wasm-bindgen-cli --version 0.2.108
      - run: cargo install -f wasm-pack
      - run: wasm-pack build -m no-install --no-typescript -t web -d wasm --out-name wasm --no-pack --release
      - run: cargo fmt -- --check
  audit:
    name: Cargo audit
    runs-on: [self-hosted, linux, x64]
    container:
      image: rust:1.93.0-alpine
    steps:
      - uses: actions/checkout@v4
      - run: apk add musl-dev
      - run: cargo install cargo-audit
      - run: cargo audit --ignore RUSTSEC-2021-0146 --ignore RUSTSEC-2023-0028 --ignore RUSTSEC-2023-0050 --ignore RUSTSEC-2023-0081 --ignore RUSTSEC-2024-0436
